from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import requests
import uuid
import os
from dotenv import load_dotenv
import re
import json
# Load variables from .env
load_dotenv()
API_KEY = os.getenv("API_KEY") 

# Initialize the FastAPI app
app = FastAPI(title="Langflow Orchestrator API")

# Define the exact data structure your API expects to receive
class UserRequest(BaseModel):
    profile: str
    question: str
    goals: str

# Our reusable Langflow function
def call_langflow(flow_endpoint: str, tweaks_dict: dict):
    url = f"http://localhost:7860/api/v1/run/{flow_endpoint}"
    
    payload = {
        "session_id": str(uuid.uuid4()),
        "tweaks": tweaks_dict
    }
    
    headers = {
        "x-api-key": API_KEY,
        "Content-Type": "application/json"
    }
    
    try:
        response = requests.post(url, json=payload, headers=headers)
        response.raise_for_status()  
        response_data = response.json()

        component_outputs = response_data.get("outputs", [])
        if component_outputs:
            inner_outputs = component_outputs[0].get("outputs", [])
            for output in inner_outputs:
                text_data = output.get("results", {}).get("text", {}).get("data", {}).get("text", "")
                if text_data: 
                    return text_data
                    
        return "No text output was generated by the flow."

    except Exception as e:
        return f"Error communicating with Langflow: {str(e)}"

# Define the actual API endpoint
@app.post("/process-fitness-data")
async def process_data(request: UserRequest):
    if not API_KEY:
        raise HTTPException(status_code=500, detail="API Key missing in environment variables.")
    
    # 1. Ask AI Flow
    ask_ai_tweaks = {
        "TextInput-9rWSc": {"input_value": request.profile},
        "TextInput-RJCs0": {"input_value": request.question}
    }
    ai_advice = call_langflow("ask-ai-v2", ask_ai_tweaks)

    # 2. Macro Flow
    macro_tweaks = {
        "TextInput-CIpua": {"input_value": request.profile},
        "TextInput-DIFCq": {"input_value": request.goals}
    }
    macros = call_langflow("macro-flow", macro_tweaks)

    # Helper to remove markdown and parse string to actual JSON object
    def clean_json_string(raw_string):
        # Remove markdown code blocks if they exist
        clean_str = re.sub(r"```json\n?|```", "", raw_string).strip()
        try:
            return json.loads(clean_str)
        except:
            return clean_str

    return {
        "status": "success",
        "data": {
            "advice": ai_advice,
            "macros": clean_json_string(macros)
        }
    }